<?php
function mixed_mode_auth_form_alter(&$form, &$form_state, $form_id) {
  $values = array();
  // Form specific changes
  switch ($form_id) {
    case "user_register":
      // Display mma page if mm
      //isset(variable_get('mixed_mode_auth_reg_form', true))
      if (true) {
        return mixed_mode_auth_reg_form($form);
      }
      break;
      /*
    case "user_login":
      $values['size'] = 60;
      mixed_mode_auth_login_form($values, $form);
      break;
    case "user_login_block":
      $values['size'] = 15;
      mixed_mode_auth_login_form($values, $form);
      break;
      */
  }
}

function mixed_mode_auth_reg_form(&$form) {
  $form = array();
    $form['mma_method'] = array(
    '#type' => 'radios',
    '#title' => t('Login method'),
    '#options' => array(
      t('Use Calnet'),
      t('Use this site'),
    ),
    '#description' => t('If you are UC Berkeley staff, student, or affiliate,  .'),
    //'#default_value' => $edit['custom'],
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
  );
  return $form;
  
}
function mixed_mode_auth_form_submit($form, &$form_state) {
  if ($form_state['clicked_button']['#id'] == 'edit-mma-next') {

  }

}

  /*
function mixed_mode_auth_login_form($values = array(), &$form) {

  $form['email'] = array(
                             '#type' => 'textfield',
                             '#title' => 'Email',
  //TODO: maxlength dep on db field size
                             '#maxlength' => 60,
                             '#size' => $values['size'],
                             '#required' => true, 
                             '#weight' => 0,
  //TODO: value from admin form
                             '#description' => 'Please use your berkeley.edu email if you are a UC Berkeley employee',
  );
  //  $form['submit']['#value'] = 'Next'; //TODO: configurable
  array_unshift($form['#validate'], 'mixed_mode_auth_login_validate');

  drupal_add_js(drupal_get_path('module', 'mixed_mode_auth') . '/js/mixed_mode_auth.js');
  $mma_cas_uri = array('cas_uri' => variable_get('cas_uri', '/cas'));
  drupal_add_js(array('mma' => $mma_cas_uri), 'setting');
  return $form;

}
  */

/*
 function mixed_mode_auth_login_validate($form, &$form_state) {

 //won't catch something like bwood@.berkeley.edu nor bwood@..berkeley.edu, but that will fail the email module's validation so we're cool.

 if (preg_match("/.*(@berkeley.edu{0,1}|@[-A-Za-z0-9_.]*[.]{1}berkeley.edu)$/i", $form_state['values']['email'][0]['email']) <= 0) {
 //no match, proceed with standard login
 return;
 }
 else {
 //match bounce to cas
 }

 }
 */ 