<?php

define('CAS_URI', preg_replace('@^/@', '', variable_get('cas_uri', '')));
define('COOKIE_EXPIRES', time() + 60*60*24*365*10);
define('COOKIE_PATH', '/');

/**
 * Implementation of hook_menu_alter().
 *
 * @param $items Associative array of menu router definitions returned from hook_menu().
 */
function ucb_mma_menu_alter(&$items) {
  $items['user/register'] = array(
    'title' => 'User Registration',
    'description' => '',
    'page callback' => 'ucb_mma_user_registration_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );

  $items['user'] = array(
    'title' => '',
    'description' => '',
    'page callback' => 'ucb_mma_user_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );

}

/**
 * user page: login or view user data
 */
function ucb_mma_user_page() {
	global $_REQUEST, $_COOKIE; //TODO
	
	if ($_COOKIE['mma_method'] === '0') {
		include_once(drupal_get_path('module', 'cas') . '/cas.module');
	  return drupal_get_form('cas_login_block');			
	} 
	elseif  ($_COOKIE['mma_method'] === '1') {
	  return drupal_get_form('user_login');					
	}
	else {
		drupal_set_title('Choose Login Method');
	  return drupal_get_form('ucb_mma_login');					
	}
}

/**
 * user registration page
 */
function ucb_mma_user_registration_page($step = 0) {
	if ($step == 0) {
	  return drupal_get_form('ucb_mma_register');	
	}
	elseif ($step == 1) {
		drupal_set_title("User Registration: Step 2");
		return drupal_get_form('user_register');	
	}
}

/**
 * 
 * ucb_mma user registration form
 */
function ucb_mma_register() {
  $form = array();
  $form['mma_method'] = array(
    '#type' => 'radios',
    '#title' => t('Login method'),
    '#options' => array(
      t('Use Calnet'),
      t('Use this site'),
    ),
    '#description' => t('If you are UC Berkeley staff, student, or affiliate, choose Calnet.<br />Everyone else choose "this site."'),
    //'#default_value' => $edit['custom'],
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
  );
  return $form;  
}

function ucb_mma_register_submit($form, &$form_state) {
		switch ($form_state['values']['mma_method']) {
  	case '0':
  	  setcookie('mma_method', '0', COOKIE_EXPIRES, COOKIE_PATH);
  	  drupal_goto(CAS_URI);
  		break;
    case 1:
    	setcookie('mma_method', '1', COOKIE_EXPIRES, COOKIE_PATH);
    	drupal_goto('user/register/1');
  		break;
    default:
    	watchdog('ucb_mma', 'Invalid authentication type.', '', WATCHDOG_ERROR);
  }
}

/**
 * 
 * ucb_mma user registration form
 */
function ucb_mma_login() {
  $form = array();
  $form['mma_method'] = array(
    '#type' => 'radios',
    '#title' => t('Login method'),
    '#options' => array(
      t('Use Calnet'),
      t('Use this site'),
    ),
    '#description' => t('If you are UC Berkeley staff, student, or affiliate, choose Calnet.<br />Everyone else choose "this site."'),
    //'#default_value' => $edit['custom'],
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
  );
  return $form;  
}

function ucb_mma_login_submit($form, &$form_state) {
	switch ($form_state['values']['mma_method']) {
  	case '0':
  	  setcookie('mma_method', '0', COOKIE_EXPIRES, COOKIE_PATH);
  		break;
    case 1:
    	setcookie('mma_method', '1', COOKIE_EXPIRES, COOKIE_PATH);
  		break;
    default:
    	watchdog('ucb_mma', 'Invalid authentication type.', '', WATCHDOG_ERROR);
  }
  drupal_goto('user');
}
