<?php
/**
 * Implementation of hook_menu_alter().
 *
 * @param $items Associative array of menu router definitions returned from hook_menu().
 */
function ucb_mma_menu_alter(&$items) {
  $items['user/register'] = array(
    'title' => 'User Registration',
    'description' => '',
    'page callback' => 'ucb_mma_user_registration_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );

  $items['user'] = array(
    'title' => '',
    'description' => '',
    'page callback' => 'ucb_mma_user_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );

}

/**
 * user page: login or view user data
 */
function ucb_mma_user_page() {
	global $_REQUEST, $_COOKIE; //TODO
	
	if ($_COOKIE['mma_method'] === '0') {
		//not needed //include_once(drupal_get_path('module', 'cas') . '/user.module');
	  return drupal_get_form('cas_login_block');			
	} 
	elseif  ($_COOKIE['mma_method'] === '1') {
		//not needed //include_once(drupal_get_path('module', 'user') . '/user.module');
	  return drupal_get_form('user_login');					
	}
	else {
		drupal_set_title('Choose Login Method');
	  return drupal_get_form('ucb_mma_login');					
	}
}

/**
 * user registration page
 */
function ucb_mma_user_registration_page($step = 0) {
	if ($step == 0) {
	  return drupal_get_form('ucb_mma_register');	
	}
	elseif ($step == 1) {
		drupal_set_title("User Registration: Step 2");
		return drupal_get_form('user_register');	
	}
}

/**
 * 
 * ucb_mma user registration form
 */
function ucb_mma_register() {
  $form = array();
  $form['mma_method'] = array(
    '#type' => 'radios',
    '#title' => t('Login method'),
    '#options' => array(
      t('Use Calnet'),
      t('Use this site'),
    ),
    '#description' => t('If you are UC Berkeley staff, student, or affiliate, choose Calnet.<br />Everyone else choose "this site."'),
    //'#default_value' => $edit['custom'],
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
  );
  return $form;  
}

function ucb_mma_register_submit($form, &$form_state) {
	$tenyrs = 60*60*24*365*10;
	if ($form_state['values']['mma-method'] === 0) {
    setcookie('mma_method', 0, time() + $tenyrs);
		drupal_goto(variable_get('cas_uri'));
  }
  else {
  	setcookie('mma_method', 1, time() + $tenyrs);
  	drupal_goto('user/register/1');
  }

}

/**
 * 
 * ucb_mma user registration form
 */
function ucb_mma_login() {
  $form = array();
  $form['mma_method'] = array(
    '#type' => 'radios',
    '#title' => t('Login method'),
    '#options' => array(
      t('Use Calnet'),
      t('Use this site'),
    ),
    '#description' => t('If you are UC Berkeley staff, student, or affiliate, choose Calnet.<br />Everyone else choose "this site."'),
    //'#default_value' => $edit['custom'],
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
  );
  return $form;  
}

function ucb_mma_login_submit($form, &$form_state) {
	if ($form_state['values']['mma-method'] === 0) {
    setcookie('mma_method', 0);
		drupal_goto(variable_get('cas_uri'));
  }
  else {
  	setcookie('mma_method', 1);
  	drupal_goto('user');
  }

}

  /*
function ucb_mma_login_form($values = array(), &$form) {

  $form['email'] = array(
                             '#type' => 'textfield',
                             '#title' => 'Email',
  //TODO: maxlength dep on db field size
                             '#maxlength' => 60,
                             '#size' => $values['size'],
                             '#required' => true, 
                             '#weight' => 0,
  //TODO: value from admin form
                             '#description' => 'Please use your berkeley.edu email if you are a UC Berkeley employee',
  );
  //  $form['submit']['#value'] = 'Next'; //TODO: configurable
  array_unshift($form['#validate'], 'ucb_mma_login_validate');

  drupal_add_js(drupal_get_path('module', 'ucb_mma') . '/js/ucb_mma.js');
  $mma_cas_uri = array('cas_uri' => variable_get('cas_uri', '/cas'));
  drupal_add_js(array('mma' => $mma_cas_uri), 'setting');
  return $form;

}
  */

/*
 function ucb_mma_login_validate($form, &$form_state) {

 //won't catch something like bwood@.berkeley.edu nor bwood@..berkeley.edu, but that will fail the email module's validation so we're cool.

 if (preg_match("/.*(@berkeley.edu{0,1}|@[-A-Za-z0-9_.]*[.]{1}berkeley.edu)$/i", $form_state['values']['email'][0]['email']) <= 0) {
 //no match, proceed with standard login
 return;
 }
 else {
 //match bounce to cas
 }

 }
 */ 